volumes:
  pnpmstore:
services:
  dev:
    user: 1001:1001
    build: 
      dockerfile: Dockerfile
    volumes:
      - ./projects:/user/projects
      - pnpmstore:/user/projects/.pnpm-store
    ports:
      - 5173:5173
      - 4096:4096
