set-option -sa terminal-overrides ",xterm*:Tc"

set -g mouse on 
set -g extended-keys on
set -g extended-keys-format csi-u

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @catppuccin_flavor 'mocha'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
